### ISSUE TITLE
Can i ask for clarifications?

### ISSUE THREAD

**Issue by CarbuncleOrigin** [iamRusty/Sentiment-Analysis-of-Filipino-Tweets#1]
In your paper, in the "Data Gathering" section it is stated "The whole dataset was
then built with 92% (3177 tweets) as training set and 8% (256 tweets) as test set".  
3422 in total.

However, in the "Results and Discussion" section it is stated that "1698 positive tweets and 2410 negative tweets were used to train the model and 128 tweets each of positive and negative were used to evaluate the model". 
4108 in total.
Were there any typo errors here? because 3422 != 4108

Furthermore, 
tf_buildata_clean.py trains on 3400, validate on 381 samples. 3781 in total.
I tested the clean.py and got an overall test accuracy of 62.49%. (averaged the mean of the 10 epochs)
Why didn't this achieve the expected 70% test accuracy?
                     
tf_buildata.py trains on 19139, validate 381 samples. 19520 in total.
I got an overall test accuracy of 71.55% across 5 epochs. 
What's the reason behind the use of repeated data?

**Comment by iamRusty** [comment]
It's been more than a year since I made this project and honestly, I can't remember why I put 4100 instead of 3400 tweets in the abstract. I'm guessing that the values came from the early results of the project and that I had not updated the abstract in the final revision. The paper has gone through a lot of revision and afaik, the results and discussion part best reflects the project (which means that 3400 should be . Nonetheless, the code tf_builddata_clean.py  should give the correct number of tweets used for training and testing. 

As for the the last 2 paragraphs, have you tried adjusting the batch_size(line 118) and the LAST "units"(line 122). 
I didn't use tf_builddata.py for the analysis. In fact, there's no reason to use repeated data for training, much more for testing. I only used it as a  as a proof of concept, building on my early dataset when I still haven't cleaned(remove repeated tweets, remove unnecessary characters, etc) the tweets.

Also, if I remember correctly, the optimization doesn't converge so you should use different number of epochs in training.

**Comment by CarbuncleOrigin** [comment]
Thank you for the quick response! :)
I'm currently testing by using different batch sizes (line 118), units (line 122), and number of epochs (line 137). I will update you once I'm finished.

Just an additional question, are lines 107-110 necessary? the comment seems to say otherwise.
# Pad Sequences ?? THE HECK IS THIS ??
x_train = sequence.pad_sequences(x_train, maxlen=maxlen)
x_test_neg = sequence.pad_sequences(x_test_neg, maxlen=maxlen)
x_test_pos = sequence.pad_sequences(x_test_pos, maxlen=maxlen)
x_test = sequence.pad_sequences(x_test, maxlen=maxlen)

**Comment by iamRusty** [comment]
If I remember correctly, no, they were not necessary.

**Comment by CarbuncleOrigin** [comment]
These are the results of testing tf_buildata_clean.py, modifying only the following: batch_size, units, and epoch.
I have not excluded the lines 107-110 in these testings.
(batch size, units, no. of epoch, accuracy)
16	32	1	62.65
16	64	1	61.99
16	128	1	60.76
16	256	1	61.00
32	32	1	64.28
32	64	1	62.76
32	128	1	61.99
32	256	1	62.97
64	32	1	63.83
64	64	1	63.28
64	128	1	63.91
64	256	1	62.23
128	32	1	64.28
128	64	1	63.67
128	128	1	62.31
128	256	1	62.47
16	32	5	60.05
16	64	5	59.40
16	128	5	60.34
16	256	5	59.21
32	32	5	60.71
32	64	5	59.48
32	128	5	60.10
32	256	5	59.50
64	32	5	59.45
64	64	5	59.74
64	128	5	60.68
64	256	5	60.16
128	32	5	60.00
128	64	5	60.58
128	128	5	60.52
128	256	5	60.05
16	32	10	58.98
16	64	10	59.84
16	128	10	58.08
16	256	10	59.53
32	32	10	58.16

I'm interested in knowing the accuracy because I'll be including your research as part of my thesis (related studies). The basis for the accuracy is the provided code but so far, it does not reflect the expected results.

**Comment by CarbuncleOrigin** [comment]
I excluded the lines 107-110 (padding sequences) but got this error. It seems to be necessary.

ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 3400 arrays: [array([[1148],
       [ 691], ...
