### ISSUE TITLE
Concerns about Data Gathering

### ISSUE THREAD

**Issue by RoiOng** [iamRusty/Sentiment-Analysis-of-Filipino-Tweets#2]
Hello! I would just like to ask. How did you gather data from twiter specifically the filipino language? And you've mentioned that you will post the scripts for processing JSON of tweets to text of tweets and for getting stream of Tweets. Can you enlighten me with details? Hoping for your positive response.

**Comment by iamRusty** [comment]
Hello Roi,

I used[ NLTK](http://www.nltk.org/howto/twitter.html) for scrapping tweets. And then I used [this](https://github.com/s/preprocessor) for cleaning the tweets. Unfortunately, I forgot to upload the scrapping scripts as well as the raw dataset (JSON) used for this project before reformatting my laptop so GG. 

Oh by the way, if ever you build your own dataset, I suggest that you label them manually, instead of relying on the emoticons contained in the tweets. I know it's cumbersome to label them 1 by 1 but it's worth using a good dataset.

**Comment by RoiOng** [comment]
Thank you for responding. It is unfortunate that your files are now gone. Just some follow up questions. How long does it take to train tweets ranging between 5k-10k tweets? And what does manual labelling mean, does it really make a difference? Can you give a thorough explanation or scenario? :D

**Comment by iamRusty** [comment]
I'm guessing that it won't take more than 5 minutes on a GTX 1060.

Manual labelling means you read the tweets one by one and decide for yourself the sentiments they carry (positive or negative). In contrast, auto labeling uses features to label datasets (e.g. I used smileys to determine the sentiments of a tweet). 

Does it make a difference? For sure they will make a difference. Smileys are not accurate representations of the sentiment of a tweet. A good example would be a tweet with sarcastic tone. Now you may be wondering why I used smileys as labeling tool, considering what I said just a few sentences ago. Well, the reason was simple, I didn't have the time to manually label all the tweets in my dataset... I was doing an internship that is 3 hours away from my school while doing this project. 

So yeah, I am really encouraging you to make your dataset as clean as possible. One way to ensure that your dataset is good is to manually label them.

**Comment by RoiOng** [comment]
Im sorry. I made a mistake. What I meant was how long would it take to gather the raw data and clean the said data. I am new to these stuff, a beginner :D.

**Comment by iamRusty** [comment]
It took me 3 days or more to gather my dataset. And that was me using a slow internet connection, I would could collected more if I had the proper resources. My advice would be to leave your scraping script running on daytime. While collecting tweets, try to experiment on cleaning sample tweets .

**Comment by RoiOng** [comment]
Hii again. I have a question. Given the ff conditions:
### Max Internet Speed of 300kbps
### GPU is GTX 1060

How long do you think will it take to do all of these tasks (this is in order):
1. Data Gathering - gathering of raw/unprocessed data using Twitter API
2. Preprocessing - removal of hashtags, URLs, user mentions, etc...
3. Manual Checking - check if the tweets contain atleast one Filipino word (to satisfy the project scope). If false the tweet will not proceed to step 4.
4. Manual labelling - label each tweet as either positive or negative.

... until there are 10k labeled tweets (5k positive, 5k negative)

**Comment by iamRusty** [comment]
Sorry for the late reply. Minus the manual labeling, a week is enough,

**Comment by RoiOng** [comment]
Thank you for your response
